type: recommender_training
books_path: "Data/final_books.csv"
interactions_path: "Data/interaction.csv"
n_factors: 20
max_iter: 200
sample_size: 10000
registered_model: "ml_catalog.ml_schema.popularity"
regularization: 0.01
max_features: 5000
w_cbf: 0.7
w_pop: 0.2
w_mf: 0.1